export const ACTION_GET_BOOKMARK_FROM_URL = 'ACTION_GET_BOOKMARK_FROM_URL';
export const ACTION_GET_POPUP_INFO = 'ACTION_GET_POPUP_INFO';
export const ACTION_ADD_BOOKMARK = 'ACTION_ADD_BOOKMARK';
export const ACTION_DELETE_BOOKMARK = 'ACTION_DELETE_BOOKMARK';

export const ERROR_INVALID_URL = 'ERROR_INVALID_URL';
export const ERROR_EMPTY_AUTH_TOKEN = 'ERROR_EMPTY_AUTH_TOKEN';
export const ERROR_INVALID_AUTH_TOKEN = 'ERROR_INVALID_AUTH_TOKEN';

export const OPTIONS_AUTH_TOKEN = 'OPTIONS_AUTH_TOKEN';
export const OPTIONS_PRIVATE = 'OPTIONS_PRIVATE';
export const OPTIONS_READ_LATER = 'OPTIONS_READ_LATER';
export const OPTIONS_PIN_IN_GOOGLE = 'OPTIONS_PIN_IN_GOOGLE';
export const OPTIONS_AUTH_TOKEN_IS_VALID = 'OPTIONS_AUTH_TOKEN_IS_VALID';
export const OPTIONS_QUICK_ADD = 'OPTIONS_QUICK_ADD';

export const OPTIONS_DEFAULT = {
  [OPTIONS_AUTH_TOKEN]: '',
  [OPTIONS_PRIVATE]: true,
  [OPTIONS_READ_LATER]: false,
  [OPTIONS_PIN_IN_GOOGLE]: false,
  [OPTIONS_AUTH_TOKEN_IS_VALID]: false,
  [OPTIONS_QUICK_ADD]: true,
};
